### ISSUE TITLE
[Request] Only load alloys when they have a use

### ISSUE THREAD

**Issue by Voxel-Friend** [ZengineeringTeam/Foundry#24]
Please have alloys only be loaded if the material has an ingot supplied by another mod. For example, I have the ingredients to make bronze, but no mod I have installed uses it. So I have recipes for a molten liquid that I cannot use and a cauldron appearing in JEI that cannot be obtained. I request this as I am creating a modpack aimed to be as streamlined as possible, with zero content overlap and highly consistent and bug free.

**Comment by Snownee** [comment]
How about hiding these recipes in JEI?

**Comment by Voxel-Friend** [comment]
Because I dont want my players accidentally creating an alloy they cannot use.

**Comment by SimonMeskens** [comment]
What I'm doing in my pack is just removing these recipes, but I've already mentioned wanting to PR in this exact change at some point. I'll have a look at it soon. IIRC, the issue is that at time of liquid creation, you don't have access to all registered items, so checking for existing ingots is not a possibility. The option to enable/disable metals in the config is possible though and I might do that.

**Comment by Voxel-Friend** [comment]
A solution would be to detect what mods are loaded and if there isn't a molten metal registered yet for the metals in that particular mod, register it. It would involve code to support for each major mod though. The main ones I would think matter are Thermal Foundation, Immersive Engineering, Ender IO, Tinkers Construct, and Base Metals.

**Comment by Voxel-Friend** [comment]
Something like:
if immersiveengineering is loaded
    if molten nickel is not created
        create molten nickel
    if molten steel is not created
        create molten steel

**Comment by SimonMeskens** [comment]
Yup, that's what I'm working on, but I've been busy the last week. It'll come.

**Comment by Voxel-Friend** [comment]
Nice. No rush, just glad it's coming.
